### ISSUE TITLE
query_workitems in storage.rb not compatible with ruote-kit 

### ISSUE THREAD

**Issue by fvanclef** [jmettraux/ruote-sequel#1]
Hello

I am using ruote-kit with a sequel storage but ruote-kit is using a :skip parameter instead of a :offset parameter for workitem query. I had to change a line in the code of the storage.rb file in order to make it compatible 

278     offset = criteria.delete('offset') || criteria.delete('skip')

Best regards

Frédéric

**Comment by jmettraux** [comment]
Hello Frédéric,

the issue was fixed in https://github.com/jmettraux/ruote-sequel/commit/38bba4cffb53a52aefd23e7bc3cbce544c0d22a1

It will be part of the upcoming 2.2.1 release.

Many thanks for your feedback.
